apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro2026-webapp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <GIT_REPO_URL>
    targetRevision: main
    path: manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: kro2026
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
